import type {
  AppNotification,
  Booking,
  FeedPost,
  Memory,
  Pet,
  Profile,
  ReviewSummary,
  ServiceOffer,
  ServiceRequest,
  Video,
} from "@/lib/types";

export const demoProfile: Profile = {
  id: "demo",
  display_name: "PetLife 用户",
  phone: null,
  city: "上海",
  bio: "在 PetLife 记录宠物成长，也认识同频的宠物家庭。",
  avatar_symbol: "pawprint",
  verification_status: "verified",
  response_rate: 96,
  response_time_label: "通常 10 分钟内回复",
  rating_avg: 4.9,
  rating_count: 18,
  repeat_booking_count: 6,
  completed_booking_count: 23,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const demoPets: Pet[] = [
  {
    id: "demo-bobo",
    owner_id: "demo-owner",
    name: "Bobo",
    species: "狗狗",
    breed: "柯基",
    age_text: "2岁",
    city: "上海",
    bio: "情绪稳定，喜欢飞盘和草地社交，见面会先闻闻再摇尾巴。",
    interests: ["飞盘", "露营", "亲人"],
    looking_for: "周末能一起跑起来的玩伴",
    accent: "peach",
    vaccinated: true,
    visibility: "public",
    sex: "male",
    personality_tags: ["外向", "黏人", "适应快"],
    energy_level: "high",
    social_level: "outgoing",
    health_summary: "已完成基础疫苗，适合线下见面",
    vaccine_status: "complete",
    neutered_status: "yes",
    avatar_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-mochi",
    owner_id: "demo-owner",
    name: "Mochi",
    species: "猫咪",
    breed: "布偶猫",
    age_text: "1岁半",
    city: "杭州",
    bio: "慢热但很黏人，适合安静家庭，也愿意先从线上视频认识。",
    interests: ["晒太阳", "陪伴", "安静"],
    looking_for: "性格温柔的长期陪伴对象",
    accent: "sky",
    vaccinated: true,
    visibility: "public",
    sex: "female",
    personality_tags: ["慢热", "稳定", "亲近后很黏"],
    energy_level: "medium",
    social_level: "warm",
    health_summary: "基础健康信息完整，可先视频互动",
    vaccine_status: "complete",
    neutered_status: "unknown",
    avatar_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoMemories: Memory[] = [
  {
    id: "demo-memory",
    owner_id: "demo",
    title: "初雪见面",
    subtitle: "把领养那天的照片挂上树梢，像点亮新的家庭故事。",
    date_text: "2025.12.03",
    story: "第一次见面是在下雪天。它从航空箱里探出头时很安静，但那一瞬间我们知道它要成为家里的一员。",
    ornament: "sparkles",
    accent: "ember",
    photo_path: null,
    audio_path: null,
    audio_display_name: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoVideos: Video[] = [
  {
    id: "demo-video",
    owner_id: "demo",
    title: "Lucky 第一次学会握手",
    duration_text: "00:34",
    caption: "训练第三天终于学会握手，奖励了两颗冻干。",
    tags: ["训练", "成长"],
    status: "published",
    asset_path: "",
    selected_asset_count: 1,
    accent: "ember",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoPosts: FeedPost[] = [
  {
    id: "demo-post",
    author_id: "demo-owner",
    related_pet_id: "demo-bobo",
    pet_name: "Bobo",
    topic: "找玩伴",
    city: "上海",
    content: "春天到了，想给狗狗找一个脾气温和、疫苗齐全的玩伴，也欢迎先线上视频认识。",
    tags: ["找玩伴", "疫苗齐全", "视频初聊"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoServiceOffers: ServiceOffer[] = [
  {
    id: "service-bobo",
    provider_id: "demo-owner",
    provider_name: "Bobo 的主人",
    related_pet_id: "demo-bobo",
    related_pet_name: "Bobo",
    service_types: ["宠物玩伴", "周末陪伴"],
    service_area: "上海 · 徐汇 / 长宁",
    price_mode: "按次沟通",
    availability_summary: "本周六下午可约",
    trust_badges: ["实名已验证", "6 次复购", "宠物信息完整"],
    response_time_label: "通常 10 分钟内回复",
    rating_avg: 4.9,
    rating_count: 18,
    repeat_booking_count: 6,
    intro: "适合希望先轻松认识、再约线下散步的宠物家庭。",
  },
  {
    id: "service-mochi",
    provider_id: "demo-owner",
    provider_name: "Mochi 的主人",
    related_pet_id: "demo-mochi",
    related_pet_name: "Mochi",
    service_types: ["宠物陪伴", "视频初聊"],
    service_area: "杭州 · 滨江 / 西湖",
    price_mode: "先聊后定",
    availability_summary: "工作日晚间可约",
    trust_badges: ["身份资料完整", "评价稳定", "适合慢热宠物"],
    response_time_label: "通常 20 分钟内回复",
    rating_avg: 4.8,
    rating_count: 11,
    repeat_booking_count: 4,
    intro: "更适合安静、慢热的陪伴场景，可先线上确认互动节奏。",
  },
];

export const demoServiceRequests: ServiceRequest[] = [
  {
    id: "request-weekend-walk",
    requester_id: "demo",
    requester_name: "PetLife 用户",
    related_pet_id: null,
    related_pet_name: null,
    title: "想找周末一起遛宠的同城家庭",
    detail: "希望先线上沟通宠物性格和疫苗情况，再约一个开放草地短时间见面。",
    request_type: "玩伴匹配",
    city: "上海",
    preferred_time_summary: "周末下午",
    budget_summary: "先沟通，后续按次确认",
    status: "open",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoReviewSummary: ReviewSummary = {
  rating_avg: 4.9,
  rating_count: 18,
  highlight_tags: ["回复快", "沟通清楚", "宠物状态稳定"],
  repeat_booking_count: 6,
  quote: "第一次见面前就把注意事项和宠物习惯讲得很清楚，整个过程让人放心。",
};

export const demoBookings: Booking[] = [
  {
    id: "booking-1",
    status: "pending",
    service_type: "宠物玩伴见面",
    scheduled_time: "本周六 15:00 - 16:30",
    participants: ["Bobo", "Lucky"],
    location_summary: "徐汇滨江草坪",
    price_summary: "首次见面免费沟通，后续再确认固定频次",
    safety_notice: "线下见面前先在消息页确认疫苗情况与应急联系人。",
  },
];

export const demoNotifications: AppNotification[] = [
  {
    id: "notification-1",
    type: "booking",
    title: "你的见面预约待确认",
    body: "Bobo 的主人已回复，可以继续确认本周六的时间和地点。",
    action_url: "/app/chats",
    read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "notification-2",
    type: "chat",
    title: "收到一条新消息",
    body: "对方想先了解宠物的社交习惯，适合从视频初聊开始。",
    action_url: "/app/chats",
    read: true,
    created_at: new Date().toISOString(),
  },
];
